version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: nrz-website
      APP_PORT: 80

  nrz-website:
    image: php:8.2-apache
    container_name: nrz-website
    ports:
      - "12000:80"
    volumes:
      - ${APP_DATA_DIR}/nrz-website/html:/var/www/html
    restart: unless-stopped
