version: "3.7"

services:
  # app_proxy:
  #   environment:
  #     APP_HOST: big-bear-umbrel-cloudflared_server_1
  #     APP_PORT: 14333

  server:
    image: wisdomsky/casaos-cloudflared:2023.7.3
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
